### ISSUE TITLE
Domkit License unclear

### ISSUE THREAD

**Issue by rcstuber** [ncannasse/domkit#27]
DomKit has no explicit license set on GitHub. Haxelib.json says BSD. Is that correct? Heaps is MIT, any reason for the difference there?

Sorry for nagging so much ;-) Happy new year!

**Comment by ConstNW** [comment]
> DomKit has no explicit license set on GitHub. Haxelib.json says BSD. Is that correct? Heaps is MIT, any reason for the difference there?
> 
> Sorry for nagging so much ;-) Happy new year!

Heaps at haxelib.json also BSD

**Comment by rcstuber** [comment]
Ping!

**Comment by rcstuber** [comment]
Thanks a lot!
