### ISSUE TITLE
Adding Bitmap to domkit component, bitmap.dom is null

### ISSUE THREAD

**Issue by bh213** [ncannasse/domkit#28]
I have a custom component (pseudo-code):

@:uiComp("ttt")
class TTTComp extends Flow implements h2d.domkit.Object{
    static var SRC = <ttt>
	</ttt>;

	public function new(?parent) {
		super(parent);
		initComponent();
	}
}

if I do the following:

final tttcomp = new TTTComp(parent);
final bitmap = new h2d.Bitmap(tile);
tttcomp.addChild(bitmap);

bitmap.dom will be null. This might be by design but as dom property is present I would expect it is possible to set it at the run-time. Or can it only be set in component constructor (<ttt><bitmap tile={tile}/></ttt>)?

Thanks!

**Comment by ncannasse** [comment]
You need to init the dom for heaps components you create by hand.

bmp.dom = domkit.Properties.create("bitmap", bmp);

Le lun. 11 janv. 2021 à 23:25, Gorazd Breskvar <notifications@github.com> a
écrit :

**Comment by bh213** [comment]
This is exactly what I have been looking for, thanks much! This should go into the docs.
