### ISSUE TITLE
Array alloc in applyStyle

### ISSUE THREAD

**Issue by trethaller** [ncannasse/domkit#32]
The call to `obj.getChildren()` causes an `hl.types.$ArrayDyn.alloc` on hashlink. 

		var obj : Model<Dynamic> = e.obj;
		for( c in obj.getChildren() ) {
			var c : Model<Dynamic> = c;
			if( c.dom == null )
				continue;
			applyStyle(c.dom, force);
		}

Considering `applyStyle` is one of the performance critical spots, maybe a tiny `#if domkit_heaps` would be worth it here?

**Comment by ncannasse** [comment]
There should be no allocation on getChildren, cf h2d.Object:

```
	#if domkit
	public var dom : domkit.Properties<h2d.Object>;
	@:dox(hide) @:noCompletion public inline function getChildren() return children;
	#end
```

**Comment by trethaller** [comment]
Alloc is caused by implicit arraydyn cast

**Comment by ncannasse** [comment]
Actually... you only need to compile with `-D domkit_heaps` which is much more efficient (not going through interface as we have typedef Model = h2d.Object)
