### ISSUE TITLE
Multiple CSS files, how to handle

### ISSUE THREAD

**Issue by bh213** [ncannasse/domkit#33]
I have multiple CSS files, main one and component specific ones. 

They are all initialized like this (pseudo code):
```
	public function new(?parent:Object) {
		super(parent);
		initComponent();
                final newStyle = new h2d.domkit.Style();
                newStyle.load(hxd.Res.comp_style);
                newStyle.addObject(x);
```
The problem is that if I insert component with its own CSS into another component with its own CSS, original styling seems to get lost. 
Example: Component `AComp` has applied `a.css`. `AComp` is inserted into `BComp`, which has the following SRC:
```
static var SRC = <b>
   <A id="a">
</B>;
```
`B` has `b.css` applied which does NOT have the same content as `a.css`. Styling of `A` component is lost. If styling (=css content) from `a.css` is copied to `b.css` everything works fine.

Are multiple CSS files supported or I am supposed to have one huge CSS file for the whole project?

**Comment by ncannasse** [comment]
You should not create a CSS per component, and not either a h2d.domkit.Style.
Create a single h2d.domkit.Style for your whole application and make sure to only addObject your "root" components (could be a single one that you add all children into it). Then call style.sync() every frame.

Regarding CSS, a single CSS for all components its the best, you can still split it into several files by using LESS or another css "compiler" tool.
