### ISSUE TITLE
Cannot compile examples on Haxe 3.4.7

### ISSUE THREAD

**Issue by infidel-** [ncannasse/domkit#5]
I've noticed the issue here: https://github.com/HeapsIO/heaps/issues/397 and thought that your promise on keeping backwards compatibility also relates to domkit (correct me if I'm wrong). Currently I'm getting this error on building examples (whether in heaps or domkit itself):

```
$ haxe test.hxml
../domkit/MarkupParser.hx:5: characters 5-13 : Unexpected abstract
```

**Comment by ncannasse** [comment]
Sorry but I don't have time atm to support domkit under 3.4.x, don't hesitate to submit a PR.
