### ISSUE TITLE
A simple component causes: "domkit.Identifier should be String"

### ISSUE THREAD

**Issue by SanBen** [ncannasse/domkit#52]
If I compile the following example:

```haxe
@:uiComp("view")
class ViewComp extends h2d.Flow implements h2d.domkit.Object {
    static var SRC = <view><text text="text" /></view>
}

class Main extends hxd.App {
    override function init() { }
    static function main() { new Main(); }
}
```

I always get the same error: _"domkit.Identifier should be String"_ and not much more.  
The full error is: _"haxe\lib\heaps/1,10,0/h2d/domkit/BaseComponents.hx:550: characters 3-37 : domkit.Identifier should be String"_  

The installed modules are as follows:
>  domkit: [git]
  format: [3.6.0]
  heaps: [1.10.0]
  hldx: [1.13.0]
  hlopenal: [1.5.0]
  hlsdl: [1.13.0]
  

<br/>
I would expect this example to compile, or is there a wrong Id being passed for some reason?

**Comment by ncannasse** [comment]
Seems like both libraries are out of sync, you need to use GIT for both domkit and heaps
